### ISSUE TITLE
Mistake in #2

### ISSUE THREAD

**Issue by Arkanii** [Snowbaha/E-transactionsBundle#3]
Hi,

Sorry, I did a mistake in my PR #2.
I used a ternary operator but it was a bad choice, if a key doesn't exist into the array we need to use a [null coalescing operator](https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce).

An example : http://sandbox.onlinephpfunctions.com/code/b3a552e3d2fa2aee1a6e6d1b2fbe44a25ac1d0ad

Can you update the service these tests please ?

Thanks and have a nice day 😄

**Comment by Snowbaha** [comment]
Hello,

Ok no problem, I was surprised because I used ?? instead of yours but if it was working, it doesn't matter to me.

I changed on the dev-master, tell me if you need other change before a new release

**Comment by Arkanii** [comment]
Hi, 

That's perfect thanks a lot, I just tested and it worked beautifully.

I close this ticket. :)
